#!/usr/bin/env python3
"""
extract_ranges.py - Extract per-style numeric ranges from the CraftBeer 2017
Beer Styles Study Guide and map them onto the 79 beers in clips/beer-styles.fct.

These numeric ranges (ABV %, IBU, SRM colour, OG, FG, CO2 volumes) are the data
the fuzzy backend uses to build membership functions grounded in real values
instead of hand-assigned weights.

Outputs (regenerated in place):
  data/beer-style-ranges.csv   auditable extracted table
  clips/beer-ranges.clp        deftemplate + deffacts for the engine

Requires `pdftotext` (poppler-utils) and the guide PDF under CraftBeer/
(gitignored). Run from anywhere:  python3 scripts/extract_ranges.py
"""
import re, csv, difflib, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PDF  = ROOT / "CraftBeer" / "Beer Styles Study Guide.pdf"
FCT  = ROOT / "clips" / "beer-styles.fct"
CSV  = ROOT / "data" / "beer-style-ranges.csv"
CLP  = ROOT / "clips" / "beer-ranges.clp"

if not PDF.exists():
    sys.exit(f"missing guide PDF: {PDF}\n(the CraftBeer/ material is gitignored — add the guide to regenerate)")

txt = subprocess.run(["pdftotext", "-layout", str(PDF), "-"],
                     capture_output=True, text=True, errors="replace").stdout
lines = txt.splitlines()

def deglyph(s):  # the PDF embeds Private Use Area glyphs for some letters
    s = "".join(ch for ch in s if not (0xE000 <= ord(ch) <= 0xF8FF))
    return re.sub(r'\s+', ' ', s).strip()

fct_names = re.findall(r'\(name "([^"]+)"', FCT.read_text(encoding="utf-8"))
fam_idx = [i for i, l in enumerate(lines) if "Famil" in l]   # one per style page

def name_above(i):
    j = i - 1
    while j >= 0 and not deglyph(lines[j]):
        j -= 1
    return deglyph(lines[j]) if j >= 0 else ""

def num(label, block):
    m = re.search(rf'(?:^|\s){re.escape(label)}\s+([\d.]+)\s*%?\s*[-–]\s*([\d.]+)\s*%?', block)
    if m: return float(m.group(1)), float(m.group(2))
    m = re.search(rf'(?:^|\s){re.escape(label)}\s+([\d.]+)\+', block)   # open-ended "40+"
    if m: return float(m.group(1)), 50.0
    m = re.search(rf'(?:^|\s){re.escape(label)}\s+([\d.]+)\s*%?(?:\s|$)', block)
    if m: return float(m.group(1)), float(m.group(1))
    return None, None

records = []
for k, fi in enumerate(fam_idx):
    end = fam_idx[k + 1] if k + 1 < len(fam_idx) else len(lines)
    block = "\n".join(lines[fi:end])
    cut = block.find("source: CraftBeer")
    if cut != -1: block = block[:cut]
    rec = {"guide_name": name_above(fi)}
    for lab, key in [("OG","OG"),("FG","FG"),("ABV","ABV"),("IBU","IBU"),("SRM","SRM"),("CO2 Volumes","CO2")]:
        rec[key+"_lo"], rec[key+"_hi"] = num(lab, block)
    records.append(rec)

norm = lambda s: re.sub(r'[^a-z0-9]', '', s.lower())
guide_norm = [(norm(r["guide_name"]), r) for r in records]

rows, unmatched = [], []
for target in fct_names:
    tn = norm(target)
    best, score = max(((r, difflib.SequenceMatcher(None, tn, gn).ratio()) for gn, r in guide_norm),
                      key=lambda t: t[1], default=(None, 0.0))
    if best and score >= 0.6 and best["ABV_lo"] is not None:
        row = {"name": target, "matched": best["guide_name"], "score": round(score, 2)}
        for k in ("OG","FG","ABV","IBU","SRM","CO2"):
            row[k+"_lo"], row[k+"_hi"] = best[k+"_lo"], best[k+"_hi"]
        # Drop catch-all spans: a range too wide to be characteristic carries no
        # information (specialty/wild styles list e.g. ABV 2.5-25, IBU 1-100).
        for k, span in (("ABV", 8), ("IBU", 50), ("SRM", 25), ("CO2", 3)):
            lo, hi = row[k+"_lo"], row[k+"_hi"]
            if lo is not None and hi is not None and (hi - lo) > span:
                row[k+"_lo"] = row[k+"_hi"] = None
        rows.append(row)
    else:
        unmatched.append(target)

CSV.parent.mkdir(exist_ok=True)
cols = ["name","ABV_lo","ABV_hi","IBU_lo","IBU_hi","SRM_lo","SRM_hi","OG_lo","OG_hi","FG_lo","FG_hi","CO2_lo","CO2_hi","matched","score"]
with CSV.open("w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=cols, extrasaction="ignore"); w.writeheader()
    for r in rows: w.writerow(r)

def rng(r, k):
    lo, hi = r.get(k+"_lo"), r.get(k+"_hi")
    return f"{lo} {hi}" if lo is not None and hi is not None else None

clp = ["; Auto-generated by scripts/extract_ranges.py from the CraftBeer 2017",
       "; Beer Styles Study Guide. Per-style numeric ranges (ABV %, IBU, SRM",
       "; colour, OG, FG, CO2 volumes) backing the fuzzy membership functions.",
       ";", "; Author: Donato Meoli", "",
       "(deftemplate beer-range",
       "   (slot name (type STRING))",
       "   (multislot abv) (multislot ibu) (multislot srm)",
       "   (multislot og) (multislot fg) (multislot co2))", "",
       "(deffacts beer-ranges"]
for r in rows:
    parts = [f'(beer-range (name "{r["name"]}")']
    for k in ("abv","ibu","srm","og","fg","co2"):
        v = rng(r, k.upper())
        if v: parts.append(f"({k} {v})")
    clp.append("   " + " ".join(parts) + ")")
clp.append(")")
CLP.write_text("\n".join(clp) + "\n")

print(f"fct beers: {len(fct_names)}   matched with ranges: {len(rows)}   no fixed ranges: {len(unmatched)}")
print(f"  -> {CSV.relative_to(ROOT)}")
print(f"  -> {CLP.relative_to(ROOT)}")
if unmatched:
    print("  styles with no fixed ranges in the guide (specialty/wild, span all values):")
    print("    " + ", ".join(unmatched))
